server:
  port: 8081
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:7878/xxl-job-admin  # xxl-job admin address list, such as "http://address" or "http://address01,http://address02"

    executor: # xxl-job executor address
      appname: xxl-job-executor-sample
      ip: 127.0.0.1
      port: 9999

      logpath: /data/applogs/xxl-job/jobhandler #xxl-job log path
      logretentiondays: -1    #xxl-job log retention days

    accessToken:        # xxl-job, access token

# log config
logging:
  config: classpath:logback.xml