server:
  port: 7878
spring:
  mvc:
    static-path-pattern: /static/**
  freemarker:
    suffix: .ftl
    content-type: text/html;charset=UTF-8
    cache: true
    template-loader-path: classpath:/template/
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request

    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      number_format: 0.##########
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:s
      classic_compatible: true
      template_exception_handler: ignore


  datasource:
      url: jdbc:mysql://localhost:3306/xxl-job?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat, wall
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      maxIdle: 10
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath:mybatis-mapper/*Mapper.xml
# xxl-job email
xxl:
  job:
    mail:
      host: smtp.163.com
      port: 25
      ssl: false
      username: ovono802302@163.com
      password: asdfzxcv
      sendNick: 任务调度平台XXL-JOB

    login:
      username: admin
      password: 123456

